# https://docs.github.com/code-security/reference/supply-chain-security/dependabot-options-reference

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    exclude-paths:
      - "www/webapp/src/modules"
      - "www/webapp/src/modules/"
      - "www/webapp/src/modules/*"
      - "www/webapp/src/modules/**"
      - "www/webapp/src/modules/**/*"
      - "www/webapp/src/modules/qrcode.vue/*"
      - "www/webapp/src/modules/qrcode.vue/**"
      - "www/webapp/src/modules/qrcode.vue/**/*"
      - "www/webapp/src/modules/qrcode.vue/package.json"
      - "www/webapp/src/modules"
      - "/src/modules"
      - "src/modules"
      - "src/modules/"
      - "src/modules/*"
      - "src/modules/**"
      - "src/modules/**/*"
      - "src/modules/qrcode.vue/*"
      - "src/modules/qrcode.vue/**"
      - "src/modules/qrcode.vue/**/*"
      - "src/modules/qrcode.vue/package.json"
    schedule:
      interval: "monthly"
      timezone: "Europe/Berlin"
      day: "monday"
      time: "05:00"
    groups:
      npm-webapp:
        patterns:
          - "*"
        dependency-type: "production"
      npm-webapp-dev:
        patterns:
          - "*"
        dependency-type: "development"
