# mostly extending from main .yml
services:
  www:
    depends_on:
    - webapp
    networks:
    - rearwebapp
    volumes:
    - ./www/90-desec.static.dev.location:/etc/nginx/sites-available/90-desec.static.location  # override webapp access
    logging:
      driver: "json-file"

  www_monitor:
    logging:
      driver: "json-file"

  dbapi:
    logging:
      driver: "json-file"

  dblord:
    logging:
      driver: "json-file"

  dbmaster:
    logging:
      driver: "json-file"

  api:
    environment:
    - DESECSTACK_API_DEBUG=True
    logging:
      driver: "json-file"

  nslord:
    ports:
     - "5311:53"
     - "5311:53/udp"
     - "127.0.0.1:8081:8081"
    logging:
      driver: "json-file"

  nsmaster:
    ports:
     - "5321:53"
     - "5321:53/udp"
    logging:
      driver: "json-file"

  rabbitmq:
    ports:
    - "15672:15672"
    logging:
      driver: "json-file"

  celery-email:
    logging:
      driver: "json-file"

  memcached:
    logging:
      driver: "json-file"

  webapp:
    build:
      context: www
      target: webapp
    volumes:
    - ./www/webapp/:/usr/src/app/
    working_dir: /usr/src/app/
    command: bash -c "npm install && npm run dev -- --host"
    environment:
    - VITE_APP_DESECSTACK_NS=${DESECSTACK_NS}
    - VITE_APP_DESECSTACK_API_SEPA_CREDITOR_ID=${DESECSTACK_API_SEPA_CREDITOR_ID}
    - VITE_APP_DESECSTACK_API_SEPA_CREDITOR_NAME=${DESECSTACK_API_SEPA_CREDITOR_NAME}
    - VITE_APP_LOCAL_PUBLIC_SUFFIXES=dedyn.${DESECSTACK_DOMAIN}
    - VITE_APP_EMAIL=support@desec.${DESECSTACK_DOMAIN}
    networks:
    - rearwebapp
    logging:
      driver: "json-file"

  openvpn-server:
    logging:
      driver: "json-file"

  openvpn-server_monitor:
    logging:
      driver: "json-file"

  prometheus:
    logging:
      driver: "json-file"

networks:
  rearwebapp:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${DESECSTACK_IPV4_REAR_PREFIX16}.100.0/24
        gateway: ${DESECSTACK_IPV4_REAR_PREFIX16}.100.1
